apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-api
  template:
    metadata:
      labels:
        app: diabetes-api
    spec:
      containers:
      - name: diabetes-api
        image: diabetes-pred-api:v1.0
        imagePullPolicy: Never   # Use local Docker image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-service
spec:
  selector:
    app: diabetes-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
